apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.appName } }
  labels:
    app: { { .Values.appName } }
spec:
  replicas: { { .Values.replicas } }
  selector:
    matchLabels:
      app: { { .Values.appName } }
  template:
    metadata:
      labels:
        app: { { .Values.appName } }
    spec: # Pod spec
      containers:
        - name: mycontainer
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
