apiVersion: v1
kind: Service
metadata:
  name: { { .Values.appName } }
  labels:
    app: { { .Values.appName } }
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30007
      name: java-port
  selector:
    app: { { .Values.appName } }
  type: NodePort
